@startuml

usecase  r as (Réservation)
usecase  rsc as (réservation \n des salles de cours)
usecase rmp as (réservation \n du matériel pédagogique)
usecase ps as(consulter planning des salles)
usecase rh as (consulter récapitulatif des horaires)
usecase eh as (editer récapitulatif des horaires)


r <|--rsc
r <|--rmp
Enseignant <|-- EnseignantRes

Enseignant -- r
Enseignant -- ps
Enseignant -- rh
Etudiant -- ps
EnseignantRes -- eh


actor Enseignant 
actor Etudiant 
actor EnseignantRes

@enduml
